with open('index.html', 'r', encoding='utf-8') as f:
    html = f.read()

# Fix the invalid HTML tags generated by previous regex
html = html.replace('" / loading="lazy"', '" loading="lazy"')

with open('index.html', 'w', encoding='utf-8') as f:
    f.write(html)
print("Invalid slashes fixed.")
